### ISSUE TITLE
Added .pot files / create pull-request?

### ISSUE THREAD

**Issue by niccokunzmann** [Stonelinks/jekyll-gettext-plugin#3]
I created [a plugin](https://github.com/fossasia/kniteditor/blob/gh-pages-source/_plugins/translate_pages.rb) based on your plugin. Reasons:
- I was using [poedit](http://poedit.net/)
  - it can update from pot files
  - updating the .po files created by v0.0.3, had destroyed translations with UTF-8 umlauts.

So, this version
- generates a .pot file
- generates a .po file for the default language
- updates the site if the po files change
  - you can press control+s in po-edit and F5 in the browser and it updates
- removes the endless loop if po-files change
- does not patch site but creates a plugin

Would you like to receive a pull-request with proper documentation?

**Comment by Stonelinks** [comment]
@niccokunzmann that would be wonderful! I stopped using jekyll years ago but I think others would welcome your improvements.

**Comment by niccokunzmann** [comment]
@Stonelinks I also added an example. Please review #4.

**Comment by Stonelinks** [comment]
Thanks! Reviewing it now

Lucas Doyle -- stonelinks.org/luke http://stonelinks.org/luke.html

**Comment by Stonelinks** [comment]
Merged and published
